//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Medician
    {
        public int id { get; set; }
        public string med_code { get; set; }
        public string med_name { get; set; }
        public string med_latin_name { get; set; }
        public string med_arabic_name { get; set; }
        public string med_chemical_name { get; set; }
        public string med_barcode { get; set; }
        public Nullable<int> med_minimum { get; set; }
        public Nullable<bool> med_state { get; set; }
        public string med_note { get; set; }
        public Nullable<int> med_com_id { get; set; }
        public Nullable<int> med_shape_id { get; set; }
        public Nullable<int> med_cat_id { get; set; }
        public Nullable<int> med_stor_shape_id { get; set; }
    }
}
