//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Medician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Medician()
        {
            this.T_Medicin_Move = new HashSet<T_Medicin_Move>();
            this.T_OPeration_Damage = new HashSet<T_OPeration_Damage>();
            this.T_OPeration_IN_Item = new HashSet<T_OPeration_IN_Item>();
            this.T_OPeration_Out_Item = new HashSet<T_OPeration_Out_Item>();
        }
    
        public int med_id { get; set; }
        public string med_code { get; set; }
        public string med_name { get; set; }
        public Nullable<int> med_minimum { get; set; }
        public Nullable<bool> med_state { get; set; }
        public string med_note { get; set; }
        public Nullable<int> med_shape_id { get; set; }
        public Nullable<int> med_cat_id { get; set; }
        public Nullable<int> med_unites_id { get; set; }
    
        public virtual T_Med_Category T_Med_Category { get; set; }
        public virtual T_Med_Shape T_Med_Shape { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Medicin_Move> T_Medicin_Move { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OPeration_Damage> T_OPeration_Damage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OPeration_IN_Item> T_OPeration_IN_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OPeration_Out_Item> T_OPeration_Out_Item { get; set; }
        public virtual T_Med_Unites T_Med_Unites { get; set; }
    }
}
