//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pharmcey_Info
    {
        public int ph_id { get; set; }
        public string code { get; set; }
        public string ph_name { get; set; }
        public string ph_pers_name { get; set; }
        public string ph_phone { get; set; }
        public string ph_mobile { get; set; }
        public string ph_adress { get; set; }
        public string ph_fax { get; set; }
        public string ph_email { get; set; }
        public string ph_logo { get; set; }
        public Nullable<bool> ph_state { get; set; }
        public string ph_note { get; set; }
    }
}
