//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Store_Operation
    {
        public decimal store_op_id { get; set; }
        public Nullable<System.DateTime> store_op_date { get; set; }
        public Nullable<System.TimeSpan> store_op_time { get; set; }
        public string entry_trans_text { get; set; }
        public Nullable<decimal> bond_id { get; set; }
        public Nullable<decimal> bond_type_id { get; set; }
        public Nullable<int> store_op_T_id { get; set; }
    }
}
