//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Store
    {
        public int store_id { get; set; }
        public string store_code { get; set; }
        public string store_name { get; set; }
        public Nullable<System.DateTime> store_start_date { get; set; }
        public string store_location { get; set; }
        public string store_mobile { get; set; }
        public Nullable<bool> store_state { get; set; }
        public string store_note { get; set; }
        public Nullable<int> store_T_id { get; set; }
    }
}
